.github/workflows/tag-release.yml
Added a workflow that builds binaries for arm and x86 and creates a release with them on a git tag with the pattern `v*.*.*`
You can check out [my fork](https://github.com/MitchellBerend/go-blueprint) for an example with `v69.420.0`
=> A github action to create a release on git tag

.github/workflows/linting.yml
A broken workflow was added in #28, this fixes the indentation errors.
=> Fixing broken linting pipeline

cmd/template/chiRoutes.go, cmd/template/echoRoutes.go, cmd/template/fiberServer.go, cmd/template/files/README.md.tmpl, cmd/template/files/air.toml.tmpl, cmd/template/files/gitignore.tmpl, cmd/template/files/main/fiber_main.go.tmpl, cmd/template/files/main/main.go.tmpl, cmd/template/files/makefile.tmpl, cmd/template/files/routes/chi.go.tmpl, cmd/template/files/routes/echo.go.tmpl, cmd/template/files/routes/fiber.go.tmpl, cmd/template/files/routes/gin.go.tmpl, cmd/template/files/routes/gorilla.go.tmpl, cmd/template/files/routes/http_router.go.tmpl, cmd/template/files/routes/standard_library.go.tmpl, cmd/template/files/server/fiber.go.tmpl, cmd/template/files/server/standard_library.go.tmpl, cmd/template/ginRoutes.go, cmd/template/gorillaRoutes.go, cmd/template/httpRoutes.go, cmd/template/main.go, cmd/template/routerRoutes.go
=> feat: move templates to embedded files

.github/workflows/generate-linter.yml, .github/workflows/linting.yml
This PR will run `golangci-lint` against all the generated repositories.
Things to improve:
- ~~Don't install `golangci-lint` for each item in the matrix~~ 
- Uses `golangci-lint` predefined action
- Add a `.golangci.yaml` file with desired linter configuration
resolve #39
=> ci: linting on generated code

cmd/create.go, cmd/ui/textinput/textinput.go
I made the project check the availability the given directory, if it does exist and it's not empty, it gives an error and exits.
The error messages when creating a project - if occurred - are now colored with #FF8700
=> Gives an error if a directory already exists. Colorized the errors when doing `create` if occurred

.github/workflows/ci.yml, cmd/ui/textinput/textinput.go, cmd/ui/textinput/textinput_test.go
I can pass two or more spaces as a project name causing it to fail. In the same way I can pass special characters that can mess with the integrity of the target file tree.
- Added function sanitizeInput. Leveraged [bubbles input Validate](https://pkg.go.dev/github.com/charmbracelet/bubbles@v0.16.1/textinput#Model.Validate) field to use said function.
- Added unit tests to the function.
- Modified linting.yml file to do continuous integration (linting and testing)
=> Project name input is not being sanitized

.goreleaser.yml
Go Release is failing due to artifacts name missing project version
Adds version to release artifacts.
=> fix: adds project version to release artifacts

cmd/program/program.go, cmd/template/framework/chiRoutes.go, cmd/template/framework/echoRoutes.go, cmd/template/framework/fiberServer.go, cmd/template/framework/files/dbRoutes/chi.go.tmpl, cmd/template/framework/files/dbRoutes/echo.go.tmpl, cmd/template/framework/files/dbRoutes/fiber.go.tmpl, cmd/template/framework/files/dbRoutes/gin.go.tmpl, cmd/template/framework/files/dbRoutes/gorilla.go.tmpl, cmd/template/framework/files/dbRoutes/http_router.go.tmpl, cmd/template/framework/files/dbRoutes/standard_library.go.tmpl, cmd/template/framework/files/makefile.tmpl, cmd/template/framework/files/routes/chi.go.tmpl, cmd/template/framework/files/routes/echo.go.tmpl, cmd/template/framework/files/routes/fiber.go.tmpl, cmd/template/framework/files/routes/gin.go.tmpl, cmd/template/framework/files/routes/gorilla.go.tmpl, cmd/template/framework/files/routes/http_router.go.tmpl, cmd/template/framework/files/routes/standard_library.go.tmpl, cmd/template/framework/files/tests/default-test.go.tmpl, cmd/template/framework/files/tests/echo-test.go.tmpl, cmd/template/framework/files/tests/fiber-test.go.tmpl, cmd/template/framework/files/tests/gin-test.go.tmpl, cmd/template/framework/ginRoutes.go, cmd/template/framework/gorillaRoutes.go, cmd/template/framework/httpRoutes.go, cmd/template/framework/routerRoutes.go
added tests to generated projects. just used standard go testing library because using testify or any other 3rd party libraries
need to install that package we don't know user want a testing library or not. i mean most people usually don't write tests tho. so sticking with standard testing good instead of using a 3rd party one
=> Feature/Tests to Generated Projects

cmd/ui/multiInput/multiInput.go
- fixes issue #116 
When pressing y to confirm choice of framework / db driver:
- use the last selected choice and not the one where the cursor currently is
- move the cursor to the last selected choice to display more clearly which one was chosen
=> Fix: use last selected choice

cmd/template/framework/files/air.toml.tmpl, cmd/template/framework/files/makefile.tmpl
Prior to this commit, running `make watch` will result in the program running in the background without any way of killing it other than looking for its PID and killing that. This changes the "cmd" in the ".air.toml" file to run `go build -o ./tmp/main ./cmd/api` instead of `make run`.
Running `make watch` prior to this commit:
It is stuck on "building..." but the program is already running in the background. ctrl+c kills air but does not kill the program running.
Running `make watch` with this commit:
program is now running as expected and doing ctrl+c kills the program properly.
- Change `cmd` in `.air.toml` to ~`make build`~ `go build -o ./tmp/main ./cmd/api`
- ~Change `make …
=> fix: change cmd in .air.toml to build instead of run

cmd/create.go, cmd/utils/utils.go, contributors.yml
When creating a new project without specifying any arguments, the non-interactive command tip showed at the end was missing the sub command (create, help, etc).
For example, before:
```
$ go-blueprint create
____  _                       _       _
|  _ \| |                     (_)     | |
| |_) | |_   _  ___ _ __  _ __ _ _ __ | |_
|  _ <| | | | |/ _ \ '_ \| '__| | '_ \| __|
| |_) | | |_| |  __/ |_) | |  | | | | | |_
|____/|_|\__,_|\___| .__/|_|  |_|_| |_|\__|
| |
|_|
What is the name of your project?
...
Tip: Repeat the equivalent Blueprint with the following non-interactive command:
• go-blueprint --name test --framework echo --driver none
```
When repeating the command …
=> fix: Missing argument [command] in non-interactive command tip

cmd/template/framework/files/makefile.tmpl
Closes #74;
Closes #111;
- Changed `make watch` to rely on command null command respons instead to check if `air` is installed of checking for GOPATH.
=> Fix/air: Deprecated $GOPATH reliability

.github/workflows/generate-linter.yml, cmd/create.go, cmd/program/program.go, cmd/ui/spinner/spinner.go, cmd/ui/textinput/textinput.go
The previous implementation for the spinner was entering interactive mode all the time, this caused GHA that would run `go-blueprint` at any point  to fail. 
This affected the generate projects linting as of now, but any action that would use the `go-blueprint create` would have had the same issue.
=> feat: add spinner v4

.goreleaser.yml
Please include a description of the problem or feature this PR is addressing.
- Item 1
- Item 2
=> Removing brew packages in go-releaser

.gitignore, cmd/program/program.go, contributors.yml
The use of Sprintf for joining file paths makes it impossible to run on windows.
- use filepath.Join instead of Sprintf to improve portability
=> Use filepath

.github/workflows/generate-linter.yml, cmd/program/program.go
- Git add files to the repository.
- Git commit the initial files with the message "Initial commit."
=> feat: add files and commit

cmd/template/framework/files/main/fiber_main.go.tmpl, cmd/template/framework/files/main/main.go.tmpl
Ran into an issue where port 8080 was already in use but the output only gave me the "cannot start server" message.
Added string formatting to panic output in main to include the error message if startup fails.
=> Include error message in panic output in main

cmd/template/framework/files/routes/fiber.go.tmpl
GoFiber package recommends using fiber.Map{} type which is an alias of map interface for easier JSON handling.
- Changed `map[string]string` type for `HelloWorldHandler` response to standard `fiber.Map{}` as recommended by the package.
=> [Enhancement]: Use fiber.Map instead of map object

cmd/create.go
Fix terminal not getting released if there is an error from `project.CreateMainFile()`
for example #159 
- Add `spinner.ReleaseTerminal()` as part of the error handling for `project.CreateMainFile()`
=> fix: release terminal

cmd/program/program.go, cmd/utils/utils.go
Address #159 
- adds check for git config name and email
=> add check for git config

cmd/template/framework/files/air.toml.tmpl, cmd/template/framework/files/makefile.tmpl, cmd/template/framework/files/nondbMakeFile.tmpl
Adding templ specific config to the files watched by air and also ensuring that the makefile commands are used for air.
Currently there is not a lot of complexity in the build process but as configuration increases, I would assume the team would want the makefile command to be the source of truth.
Resolves #171
- Added regex to ignore _templ.go files
- Added .templ files to the air toml
- Added `templ generate` to the makefiles conditionally
=> fix: Adding templ specific config to air.toml

cmd/create.go, cmd/program/program.go
Attempted fix for #175 
- I added a deferred anonymous function to check if the program panicked. If it did, it releases the terminal.
- I also added a panic to the git config check if they are not present. That combined with the deferred function mentioned previously, we shouldn't have users run into issues where the terminal doesn't release on panic.
=> Add a deferred anonymous function to release on panic

.github/workflows/ci.yml, .github/workflows/generate-linter.yml, cmd/template/advanced/files/htmx/hello.go.tmpl, cmd/template/advanced/files/htmx/hello_fiber.go.tmpl
Resolves #195
In #174 I had some syntax errors in the templates that ended up in the final generated code. Since all the CI tests passed I assumed all the projects were at least compiling. Turns out this assumption was wrong.
This pr adds the advanced flag to the linting matrix step in CI that checks the generated project. This checks for typos of just general mistakes in syntax in the generated code of the advanced features as well.
This pr also fixes all the linting errors that popped up by adding the advanced features to the checks.
~~- [ ] I have updated the documentation (if applicable)~~
=> Fix: Add build step for generated project

cmd/template/framework/files/server/fiber.go.tmpl
Add ServerHeader and AppName depends of project name
> [!NOTE]  
> This a cool feature from fiber
Example how it work:
```sh
$ go-blueprint create --name my-project --framework fiber --driver mysql
____  _                       _       _   
|  _ \| |                     (_)     | |  
| |_) | |_   _  ___ _ __  _ __ _ _ __ | |_ 
|  _ <| | | | |/ _ \ '_ \| '__| | '_ \| __|
| |_) | | |_| |  __/ |_) | |  | | | | | |_ 
|____/|_|\__,_|\___| .__/|_|  |_|_| |_|\__|
| |
|_|
..
Next steps:
• cd into the newly created project with: `cd my-project`
$ cd my-project
$ go run cmd/api/main.go
┌───────────────────────────────────────────────────┐ 
│                    my-project                     │ …
```
=> Feat [Fiber Framework] ServerHeader and AppName depends of project name

cmd/template/docker/files/docker-compose/redis.tmpl
Limiting the Docker image to version before dual licensing
#202
=> Redis-image-version

cmd/program/program.go, cmd/template/advanced/files/htmx/base.templ.tmpl, cmd/template/advanced/files/htmx/efs.go.tmpl, cmd/template/advanced/files/htmx/routes/chi.tmpl, cmd/template/advanced/files/htmx/routes/echo.tmpl, cmd/template/advanced/files/htmx/routes/fiber.tmpl, cmd/template/advanced/files/htmx/routes/gin.tmpl, cmd/template/advanced/files/htmx/routes/gorilla.tmpl, cmd/template/advanced/files/htmx/routes/http_router.tmpl, cmd/template/advanced/files/htmx/routes/standard_library.tmpl, docs/docs/advanced-flag/htmx-tmpl.md, docs/docs/creating-project/air.md, docs/docs/index.md
Move `js/` into `assets/js` and make `assets/` as a static file server, so user can easily add a custom folder like `cmd/web/assets/css/` and link it into `base.templ` if they want it. 
- modify `cmd/program/program.go` to create assets/ 
- modify htmx src in `cmd/template/advanced/files/htmx/base.templ.tmpl`
- modify `go:embed "js"`  to `go:embed "assets"`
- modify frameworks static file routes in `cmd/template/advanced/files/htmx/routes`
- modify some file tree in docs
=> move js/ into assets/js/ and make assets/ as static file server

cmd/steps/steps.go
Just a small typo in the Websocket option.
- Change "Weboscket" to "Websocket".
=> fix "Weboscket" typo

cmd/template/dbdriver/files/service/mysql.tmpl, cmd/template/dbdriver/files/service/postgres.tmpl, cmd/template/dbdriver/files/service/sqlite.tmpl
By implementing this `Close Database Connection`, it can be useful in scenarios such as graceful shutdown, for example, in Kubernetes (k8s).
- [+] feat(mysql.tmpl): add Close() method to Service interface and its implementation
- [+] docs(mysql.tmpl): add comments for Service interface and its methods
Note: By using the "log.Printf" method, it is more concise and idiomatic Go.
=> Implement [Database Template] [MySQL] [PostgreSQL] [SQLite] Close Database Connection

.github/workflows/update-htmx-version.yml
Previous workflow didn't work as expected. It was pretty hard to test it. Now, when the new HTMX is out, the issue was identified and fixed.
should open a new PR when there is a change in the HTMX version.
Logs from work that was failing for future reference:
```bash
Run VERSION_FILE=$(curl https://raw.githubusercontent.com/Melkeydev/go-blueprint/main/cmd/template/advanced/files/htmx/htmx.min.js.tmpl | grep version | awk -F'"' '{print "v" $2}')
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  106k  100  106k    0     0 …
```
=> Htmx-gh-action-fix

cmd/template/dbdriver/files/service/redis.tmpl, cmd/template/docker/files/docker-compose/redis.tmpl
This is related to the following:
- #230
> [!NOTE]
> Also note that this data is raw and must be structured, parsed, and converted basically cooking to make it look like this:
```json
{
"redis_health": {
"status": "up",
"message": "Redis connection pool utilization is high",
"stats": {
"version": "7.0.15",
"mode": "standalone",
"connected_clients": "10",
"memory": {
"used": {
"mb": "22.38",
"gb": "0.02"
},
"peak": {
"mb": "46.57",
"gb": "0.05"
},
"free": {
"mb": "1130.00",
"gb": "1.10"
},
"percentage": "1.98%"
},
"uptime_stats": "6 days, 3 hours, 37 minutes, 20 seconds",
"uptime": [
{
"day": "6"
},
{
"hour": "3"
},
{
"minute": "37"
},
{
"second": "20"
}
],
"pooling": {
"figures": { …
```
=> Enhance Health Function For Redis

cmd/template/framework/files/makefile.tmpl
The maintainer of the air project has changed the URL of the project to github.com/air-verse/air@latest, following discussion here: https://github.com/air-verse/air/issues/605 
- Changed install command in makefile template
=> fix: new url to install air

cmd/template/dbdriver/files/env/postgres.tmpl, cmd/template/dbdriver/files/service/postgres.tmpl
The current postgres service didn't accept schema and used public by default. Added support for specifying schema through envs
- added DB_SCHEMA env to postgres template
- passed search_path in dsn 
- [*] I have self-reviewed the changes being requested
=> feat: added db schema to postgres template

cmd/template/framework/files/nondbMakeFile.tmpl
The maintainer of the air project has changed the URL of the project to github.com/air-verse/air@latest, following discussion here: https://github.com/air-verse/air/issues/605
Changed install command in nondbMakeFile template
=> fix: url to install air in nondbMakeFile

README.md, cmd/create.go, cmd/flags/advancedFeatures.go, cmd/program/program.go, cmd/steps/steps.go, cmd/template/advanced/files/htmx/base.templ.tmpl, cmd/template/advanced/files/htmx/hello.templ.tmpl, cmd/template/advanced/files/tailwind/input.css.tmpl, cmd/template/advanced/files/tailwind/package.json.tmpl, cmd/template/advanced/files/tailwind/tailwind.config.js.tmpl, cmd/template/advanced/routes.go, cmd/template/framework/files/makefile.tmpl, cmd/utils/utils.go
Resolves #186 
This PR adds an option to the `--advanced` flag that let's users add Tailwind CSS framework to the project
- This change creates package.json, tailwind.config.js, input.css and output.css files
- pnpm is used to install tailwind via package.json as I couldn't test with npm
- updated Makefile to run tailwind for the build recipe. which is also used in .air.toml
=> Add Tailwind to advance options.

cmd/program/program.go
there was an extra if statement that led to the program excute an if twice
=> remove an extra if statement in program.go

cmd/utils/utils.go
The line that prints after the program exits. giving a quick command line version of the same options, had a bug in it that would show the --advanced true/false no matter what. This flag doesn't need a true or a false value to be passed in, only its inclusion is enough to go to advanced mode.
- Added check for all bool-flags, and changed the generated command accordingly. This is only applicable to advanced-flag, but will work for all bool-flags in the future.
=> bugfix: added special treatment of advanced flag in tip string

cmd/template/advanced/files/htmx/imports/fiber.tmpl, cmd/template/advanced/files/htmx/routes/fiber.tmpl
Observed that after building the final output for a project with HTMX and Fiber Server, the files in the embedded assets were not being properly served to the client (404 not found error for the htmx javascript file and the styles file).
- Used the fiber filesystem middleware to serve the required files
=> fix(fiber): Packaged assets not being served 

cmd/program/program.go, cmd/template/framework/files/makefile.tmpl, cmd/template/framework/files/tests/default-test.go.tmpl, cmd/template/framework/files/tests/echo-test.go.tmpl, cmd/template/framework/files/tests/fiber-test.go.tmpl, cmd/template/framework/files/tests/gin-test.go.tmpl, docs/docs/advanced-flag/tailwind.md, docs/docs/blueprint-core/db-drivers.md, docs/docs/blueprint-core/frameworks.md, docs/docs/creating-project/makefile.md, docs/docs/index.md
Resolves #280 
- moved handler_test.go to internal/server package and renamed to routes_test.go
- updated docs referring to handler_test.go in the previous location
=> move handler_test.go to internal/server package

.idea/.gitignore, cmd/program/program.go, cmd/template/framework/files/air.toml.tmpl, cmd/template/framework/files/makefile.tmpl
air live reload will be working on both Unixbased and Windows machines
- Related to issue ticket #282 
1. `UnixBased` with bool type is added to `Project` type
2. CheckOs() function is added for checking the UNIX-based operating system if it's not windows leaves the `UnixBased` to false by default
```go
func (p *Project) CheckOs() {
if runtime.GOOS != "windows" {
p.UnixBased = true
}
}
```
3. CheckOs() is executing in program.go:260
```go
// Define Operating system
p.CheckOs()
```
4. makefile.tmpl and air.toml.tmpl are modified
=> [bug] live reload fixed

README.md, cmd/program/program.go, cmd/template/advanced/files/websocket/imports/standard_library.tmpl
The websocket package that was used `nhooyr.io/websocket` was moved to `https://github.com/coder/websocket`
- Updated docs
- Search replaced old lib with new one
=> Updated `nhooyr.io/websocket` to `github.com/coder/websocket`

cmd/template/dbdriver/files/tests/mongo.tmpl
Typo in error message if database test fails due to container problem.
- Replaced string `postgres` with `mongodb`
=> Fix copy/paste typo in mongo.tmpl

.github/workflows/generate-linter-advanced.yml, .github/workflows/generate-linter-core.yml, cmd/create.go, cmd/program/program.go, cmd/ui/textinput/textinput.go, cmd/ui/textinput/textinput_test.go, cmd/utils/utils.go, cmd/utils/utils_test.go
go-blueprint create command was not working as expected if the user enters module name as an input rather than directory name.
Eg: go-blueprint create --name github.com/Patel-Raj/project1
This would create sub-directories github.com, Patel-Raj and project1 and then create the projects source code in project1 directory.
After this change, the Go project will be created at project1 as the root directory and the go.mod would have github.com/Patel-Raj/project1 as its module name.
Fixes: #285 
- Fetched directory name from the input string as the last token of the input when Split by /
- Relaxed the sanitization regex to allow / and . characters in the input.
- Used that the directory …
=> Accept module name as input to create command

cmd/template/framework/files/gitignore.tmpl
I believe we don't need to commit `.DS_Store` file
- Added the `.DS_Store` file, which is automatically generated by OS X, to the `.gitignore` file
=> chore: ignore .DS_Store file

cmd/template/framework/files/main/fiber_main.go.tmpl, cmd/template/framework/files/main/main.go.tmpl
When the HTTP server is created it is important to have it gracefully shut down, and that is a boilerplate code that would be nice for go-blueprint to be able to add when the code is generated.
- add graceful shutdown for the HTTP server.
- change the error message printed when the server shuts down.
- fixes #205
=> add graceful shutdown for the http server.

cmd/template/dbdriver/files/service/mongo.tmpl, cmd/template/dbdriver/files/service/mysql.tmpl, cmd/template/dbdriver/files/service/postgres.tmpl, cmd/template/dbdriver/files/service/redis.tmpl, cmd/template/dbdriver/files/service/sqlite.tmpl, contributors.yml, docs/docs/endpoints-test/mongo.md, docs/docs/endpoints-test/redis.md, docs/docs/endpoints-test/sql.md
This PR addresses the staticcheck issue (SA1006), which recommends using print-style functions when a printf-style function with no dynamic arguments is used.
- Replaced `log.Fatalf` with `log.Fatal` for simpler logging.
- Ensured proper error handling without unnecessary formatting.
=> Refactor: Replace printf-style function with print-style for dynamic format

cmd/program/program.go
This PR resolves issue #315 
In the `CreateMainFile` function located in `/cmd/program/program.go`, the error handling has been updated to ensure the terminal is properly released. Specifically:
- The function now returns an `err` so that the `spinner.ReleaseTerminal()` call can be executed ( create.go line 273 ), ensuring the terminal is released even in the event of an error.
This change helps prevent terminal lock-ups by ensuring proper cleanup
=> #315 fix: cursor error when go-blueprint create fails

cmd/template/advanced/files/htmx/base.templ.tmpl
Missing meta viewport tag in HTMX base.templ.tmpl file causes styling issues with smaller devices.
- Added meta viewport tag to head of base.templ.tmpl file.
=> bug: Added missing meta viewport tag to HTMX base.templ.tmpl file

README.md
Added missing hyphen to example command in README.md
=> fix(readme): add missing hyphen to example command

cmd/flags/database.go, cmd/flags/frameworks.go
This pull request addresses a minor issue in the documentation where a comment contained a spelling error, "past" instead of "paste." This small change improves clarity and ensures the comments are professional and understandable.
- Corrected the spelling in the comment from "past" to "paste."
=> fix: spelling error in comment: 'past' to 'paste'

docs/docs/advanced-flag/docker.md, docs/docs/advanced-flag/react-vite.md, docs/docs/endpoints-test/scylladb.md
This pull request addresses minor issues in the documentation where words contain spelling errors.
- Correct spelling for `yaml`, `with`, `management` words.
=> Fix spelling errors in docs

.github/workflows/generate-linter-advanced.yml, .github/workflows/generate-linter-core.yml, .github/workflows/testcontainers.yml, cmd/program/program.go, cmd/template/advanced/files/react/app.tsx.tmpl, cmd/template/advanced/files/react/tailwind/app.tsx.tmpl, docs/docs/advanced-flag/react-vite.md
This PR closes the issue/bug #350
- Updated program.go to create and copy `PORT` from root `.env` to `/frontend/env`.
- Updated app.tsx.tmpl in both react and tailwind features so that they use `VITE_PORT` instead of hardcoded value
=> feat: use PORT in React from backend .env created in frontend

README.md, docs/docs/installation.md
taken from @susilodev pr #347
- a quick extra step to tweak .zshrc during installation for a more straightforward setup
- as @Ujstor suggested updated the docs to make it clear for zsh users
Docs Preview:
=> docs: update installation instructions for Zsh users

cmd/template/dbdriver/files/tests/postgres.tmpl, contributors.yml
Postgres mustStartPostgresContainer expects to return a function of type func(ctx context.Context, opts ...testcontainers.TerminateOption) error but func(context.Context) error is returned.
- Wrong type is returned for postgres test, hence changed the postgres template configuration to ensure that the right type is returned when generating postgres test file.
=> fix: return type for postgres tests template

cmd/program/program.go, cmd/template/framework/files/makefile.tmpl, docs/docs/advanced-flag/react-vite.md
Creating a React project with Tailwind can take up to 10 minutes to complete. We enforce caching once the packages are downloaded.
=> fix npm cache

docs/docs/creating-project/makefile.md
The description of `itest` Make rule not being created when the driver selected is SQLite was cut.
Add the description that was lacking.
=> Fix `itest` SQLite exception description

cmd/ui/textinput/textinput.go, cmd/utils/utils.go
The PR refactors code to use `regexp.MatchString` to avoid one allocation when converting byte slice to string.
- Replace `regexp.Match(s, []byte(input))` with `regexp.MatchString(s, input)` where `input` is `string`.
This was found with the help of [`mirror`](https://golangci-lint.run/usage/linters/#mirror) linter, which can be enabled in golangci-lint config.
=> avoid allocations by using mirror functions

cmd/create.go, cmd/program/program.go, cmd/utils/utils.go
Currently when there is error on executing command it doesn't tell what the problem is and may cause confusion like #379 .
This PR aim to present more transparent error message that will for example looks like:
```shell
2025/03/13 10:15:47 Could not install go dependency for the chosen framework
2025/03/13 10:15:47 Problem creating files for project.
Error: exit status 1
go: golang.org/x/sys@v0.31.0 requires go >= 1.23.0 (running go 1.22.2)
go: golang.org/x/sys@v0.31.0 requires go >= 1.23.0 (running go 1.22.2)
go: golang.org/x/sys@v0.31.0 requires go >= 1.23.0 (running go 1.22.2)
go: golang.org/x/sys@v0.31.0 requires go >= 1.23.0 (running go 1.22.2)
```
- Change the way error …
=> more transparent error message when error executing command

.github/workflows/docs.yml
Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: v2`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
=> fix_docs_actions

cmd/program/program.go
As the @tailwindcss/vite is installed and only supports v4 we are using --prefer-offline flag that can install probably install  tailwindcss v3 from cache with this we force to use cache only is tailwindcss version is greater than v4
Added constraint so it only installs greater than v4 in the cache
"tailwindcss@^4"
=> fix: dont install less than v4 tailwindcss

cmd/create.go, cmd/utils/utils.go
Added flag completions 
- created a function in `cmd/utils/utils.go` that takes a cobra command, a string representing a flag, and an array of strings representing the posible values of the flag
- implemented the completions for advanced flags in `cmd/create/create.go` using the already defined options declared in the different modules
=> feat: add flag completions

cmd/program/program.go
Fix for the [[Bug] Panic occurs when there is no git #360](https://github.com/Melkeydev/go-blueprint/issues/360). 
I ran the tests and tested multiple combinations locally.
I saw that it was planned in another refactor PR which has been in progress for a very long time and has a lot of changes. I created this PR to just fix the bug independent of the refactoring.
Localized the call of `utils.CheckGitConfig` since it is only needed if the git flag is not set to `skip`.
=> Fixed no git on system panic even if git flag is skip

cmd/program/program.go, cmd/template/advanced/files/htmx/tailwind/tailwind.config.js.tmpl, cmd/template/advanced/routes.go
When making a Tailwind template which uses HTMX by default, there isn't any config file that signals that the LSP should be active on templ files, which means that you have to manually add it. This change aims to fix that, though I'm not sure if this change is needed when making other templates using Tailwind too, if so, I'm willing to update this PR to change those as well.
- added a new `cmd/template/advanced/files/htmx/tailwind` folder and a `cmd/template/advanced/files/htmx/tailwind/tailwind.config.js.tmpl` file
- added the `tailwind.config.js.tmpl` file to `cmd/templates/advanced/routes.go`
- added the file to `program.go`
=> Add tailwind config for Tailwind LSP support in templ files

.github/workflows/npm-publish.yml, .github/workflows/release.yml, README.md, docs/docs/installation.md, scripts/create-npm-packages.sh
This is a collaborative PR with @NachoVazquez that address the [Issue-405](https://github.com/Melkeydev/go-blueprint/issues/405). The goal is to provide NPM distribution for the Go-Blueprint library. We are using [optionalDependencies](https://github.com/evanw/esbuild/pull/1621) to handle cross-platform compatibility by deploying separate packages for each OS-architecture combination of the library binaries.
Examples can be found [here](https://www.npmjs.com/package/go-blueprint-test?activeTab=readme).
- **New workflow for NPM publishing**: Automated publishing process that runs after GoReleaser completion.
- **Build script**: Bash script that generates the platform-specific NPM …
=> Release to NPM
