cmd/template/chiRoutes.go, cmd/template/fiberServer.go, cmd/template/ginRoutes.go, cmd/template/gorillaRoutes.go, cmd/template/httpRoutes.go, cmd/template/main.go, cmd/template/routerRoutes.go
Hi,
I noticed the generated files had empty lines at the top of them.
I fixed this in my PR. It does make the actual code a bit less pretty, but I think that's a fair trade-off
=> fix: Remove the empty line at the top of generated files

cmd/template/fiberServer.go, cmd/template/main.go
Another small fix for whitespace
=> fix: remove trailing spaces

LICENSE
=> Actual MIT license

cmd/program/program.go, cmd/utils/utils.go
Not sure if this is something you want in this project, but this would make the whitespace problems a non-issue, but would make the generation of the files a bit slower.
=> feat: Add gofmt after creating the go files

contributors.yml
Made contributors.yml same as in astrostation :)
-professional jr dev o7
Resolves #33
=> Added contributors list

.pre-commit-config.yaml
Suggested feature to be supported on issue #13.
- Added .pre-commit-config.yaml
Adds a trailing whitespace at the end of every staged file. (Good practice IMO).
Checks and cleans special Unicode codes that are invisible and can mess with the file (Copy and pasted code).
Verifies general purpose yaml files.
Safeguard from adding big stuff to the repo.
=> feat: Added precommit support

cmd/program/program.go
I added one line to trim trailing and preceding whitespace.
This is my first time contributing code, much help will be appreciated. Sorry in advance!
=> Trim whitespace for ProjectName

cmd/program/program.go, cmd/template/main.go
=> Fix/air: Air Install Globally 

cmd/create.go, cmd/utils/utils.go
closes #56 
- Prints the equivalent non-interactive command with flags and values
- Only does this when in interactive mode (when no flags are set by the user)
Demo:
https://github.com/Melkeydev/go-blueprint/assets/70033855/960ffedb-4fb2-4fd0-9587-1b52373505f0
=> Print the Equivalent Non-interactive Command

.goreleaser.yml
=> fix 🐛: added hotfix to taps on homebrew

.github/issue_template/config.yml, .github/semantic.yml
The issue templates don't appear properly.
- Adds the config which I missed
- Encourages conventional commits
=> fix: templates not appearing because of config

README.md, cmd/template/framework/files/gitignore.tmpl
- Updated Readme.md
- Added `.env` in `.gitignore` file
=> Chore/update readme.md

cmd/template/dbdriver/files/service/postgres.tmpl
Added PGX as Postgres Driver since PG is unmaintained
=> Adding PGX Postgres Driver 

CONTRIBUTING.md
@mikelerch pointed out some grammar errors before the PR got merged
- Removed to instances of the as suggested
=> fix: grammatical errors

.github/workflows/generate-linter.yml, cmd/create.go, cmd/ui/spinner/spinner.go
This PR removes padding on the spinner
It removes the spinner after finishing
Adds spinner in non-interactive mode
- Changed some code
=> Spinner revamp

README.md, cmd/program/program.go, cmd/ui/multiInput/multiInput.go, cmd/ui/spinner/spinner.go
This PR will be a draft to fix some small issues. Merge after enough issues are accumulated.
No.1
- Issue  #133 
- referenced pq instead of the current postgres driver
----------------------------------------------------
No.2
-CLI visual improvements; added a space between choice and SQLite message
Before:
After:
----------------------------------------------------
=> Fix: Includes small fixes in the code

README.md
=> Readme-Fix

cmd/template/advanced/files/htmx/htmx.min.js.tmpl
The Default Template is an old version of HTMX.
- [HTMX Change Log v1.9.11](https://github.com/bigskysoftware/htmx/releases/tag/v1.9.11)
https://github.com/Melkeydev/go-blueprint/assets/17626300/affa410f-66aa-41e5-8dc9-d3931fbd07f9
=> Update HTMX to v1.9.11

cmd/template/dbdriver/files/service/redis.tmpl
This related this issues
- #226
- [+] feat(redis.tmpl): add TLS configuration to Redis connection setup
=> Implement [Database Template] [Redis] TLS configuration

docs/docs/endpoints-test/redis.md
Update Documentation for Redis Health Statistics
- [+] docs(redis.md): add a note about structuring the Sample Output using serialization
=> Docs [docs.go-blueprint.dev] Update Documentation

cmd/template/framework/files/gitignore.tmpl
I believe we don't need to commit the result of the build from Templ 
- added **/*.templ.go on gitnore tmpl  file
=> chore: ignore templ.go file

cmd/template/advanced/files/workflow/github/github_action_goreleaser.yml.tmpl, cmd/template/advanced/files/workflow/github/github_action_gotest.yml.tmpl, cmd/template/advanced/files/workflow/github/github_action_releaser_config.yml.tmpl
Added templ generate to workflow #185 
- Added templ generate to go-test
- Added templ generate to goreleaser
=> Added templ generate to workflow

cmd/program/program.go, cmd/template/framework/files/README.md.tmpl, cmd/template/framework/files/air.toml.tmpl, cmd/template/framework/files/makefile.tmpl, docs/docs/advanced-flag/htmx-templ.md, docs/docs/advanced-flag/tailwind.md, docs/docs/creating-project/makefile.md
Fixes: #275 #304 #295
Implements Tailwind CSS Makefile build and other templating instructions based on the specific OS.
=> feat: Makefile update

docs/docs/advanced-flag/docker.md
=> docker_docs

cmd/template/framework/files/gitignore.tmpl
=> Add output.css to .gitignore if Tailwind is used

.github/workflows/ci.yml, .github/workflows/generate-linter-advanced.yml, .github/workflows/generate-linter-core.yml, .github/workflows/testcontainers.yml, cmd/template/advanced/files/htmx/hello_fiber.go.tmpl, cmd/template/dbdriver/files/service/redis.tmpl, contributors.yml, docs/mkdocs.yml
Update golangci-lint to v1.63.4
=> golangci-lint v1.63.4

cmd/template/advanced/files/docker/dockerfile.tmpl, cmd/template/framework/files/makefile.tmpl
Tailwind v4.0.0 for htmx isn't generating the utility classe
close #371
=> fix:tailwind_v3.4.10

docs/docs/advanced-flag/react-vite.md, docs/docs/advanced-flag/websocket.md, docs/docs/blueprint-core/db-drivers.md, docs/docs/blueprint-core/frameworks.md, docs/docs/creating-project/project-init.md, docs/docs/endpoints-test/mongo.md, docs/docs/index.md, docs/docs/installation.md
The documentation for DB Drivers had text duplicated from the Redis description to the Sqlite description. Additionally, other parts of the documentation showed inconsistent casing and minor grammatical errors.
- Updated file tree comments to be uniform where appropriate.
- Removed erroneous words and sentence fragments across the documentation.
- Updated casing, and added/removed words as appropriate for improved readability.
=> chore: fix typos/grammar and remove duplicate text

docs/docs/advanced-flag/tailwind.md
Remove a duplicate word from the docs.
=> docs: remove duplicate word
